name: deploy

on: [push]
#  push:
#    tags:
#      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Setup

      - uses: actions/checkout@v6

      - name: Get the version
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT
            echo "PROMOTE=true" >> $GITHUB_OUTPUT
          else
            echo "VERSION=vdev" >> $GITHUB_OUTPUT
            echo "PROMOTE=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/setup-node@v6
        with:
          cache: 'npm'

      - id: 'auth'
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: 'projects/849551145524/locations/global/workloadIdentityPools/github/providers/github'
          service_account: 'github-actions@devfest2027.iam.gserviceaccount.com'

      # Build
      - run: npm ci --verbose
      - run: npm run build

      # Deploy static files to App Engine
      - run: cp .appengine/app.yaml out/app.yaml

      - id: 'deploy'
        name: 'Deploy to App Engine'
        uses: 'google-github-actions/deploy-appengine@v3'
        with:
          working_directory: 'out'
          promote: ${{ steps.get_version.outputs.PROMOTE }}
          version: ${{ steps.get_version.outputs.VERSION }}
          project_id: 'devfest2027'
